apiVersion: v1
kind: Pod
metadata:
  name: stock-crawling
  labels:
    app: my-app
spec:
  containers:
  - name: crawl
    image: crawl_app:dev
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8002
